version: 2
jobs:
  build:
    docker:
    - image: polishfiltersteam/sflb_image:3.0.4
    working_directory: ~/git/KADhosts
    steps:
    - checkout
    - run: |
        python3 SFLB.py ./KADhosts.txt ./KADhole.txt ./KADomains.txt
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: org-global
