version: 2
jobs:
  build:
    docker:
    - image: polishfiltersteam/vichs_image:latest
    working_directory: ~/git/KADhosts
    steps:
    - checkout
    - run: ./scripts/VICHS.sh ./KADhosts.txt ./KADhole.txt ./KADomains.txt
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: org-global
