version: 2
jobs:
  build:
    docker:
    - image: polishfiltersteam/vichs_image:latest
    steps:
    - checkout
    - run: ./scripts/VICHS.sh KADhosts.txt KADhosts_without_controversies.txt KADhole.txt KADfakeHosts.txt KADhostsOnline.txt
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: org-global
