version: 2
jobs:
  build:
    docker:
    - image: polishfiltersteam/vichs_image:latest
    working_directory: ~/git/KADhosts
    steps:
    - checkout
    - run: NO_PUSH="true" ./scripts/VICHS_auto.sh
    - store_artifacts:
        path: KADhosts.txt
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: org-global
