name: Aktualizacja listy

on:
  workflow_dispatch: null

jobs:
  Aktualizacja:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/sflb_image:3.0.3
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Aktualizacja całej listy
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          python3 SFLB.py ./KADhosts.txt ./KADhole.txt ./KADomains.txt
